// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { ActorNamespace as __TelnyxActorNamespace, KvNamespace as __TelnyxKvNamespace, RateLimiter as __TelnyxRateLimiter } from "@telnyx/edge-runtime";
import type { DupipCallSession } from "./src/index";
import type { default as __TelnyxClient } from "telnyx";

declare global {
  interface Env {
    CALL_SESSION: __TelnyxActorNamespace<DupipCallSession>;
    TELNYX: __TelnyxClient;
    CALLER_CACHE: __TelnyxKvNamespace;
    DYNAMIC_VARIABLES: __TelnyxRateLimiter;
    SECRETS: { get(binding: "MORPHEUS_BASE_URL" | "MORPHEUS_EDGE_SECRET" | "TELNYX_WEBHOOK_PUBLIC_KEY"): Promise<string> };
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    CALL_SESSION: __TelnyxActorNamespace<DupipCallSession>;
    TELNYX: __TelnyxClient;
    CALLER_CACHE: __TelnyxKvNamespace;
    DYNAMIC_VARIABLES: __TelnyxRateLimiter;
    SECRETS: { get(binding: "MORPHEUS_BASE_URL" | "MORPHEUS_EDGE_SECRET" | "TELNYX_WEBHOOK_PUBLIC_KEY"): Promise<string> };
  }
}

export {};
