export const locales = ['ar', 'bn', 'ca', 'cs', 'da', 'de', 'el', 'en', 'es', 'et', 'eu', 'fi', 'fr', 'gl', 'he', 'hi', 'hu', 'it', 'ja', 'ko', 'ms', 'nl', 'pa', 'pl', 'pt', 'ro', 'ru', 'sv', 'tr', 'zh']
export const defaultLocale = 'en'

export const WEEKLY_ACTIONS = [
  {
    name: 'Created content for social media',
    localeKey: 'actions.weekly.createdContent',
    area: 'social',
    categories: ['community'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Flirted with someone',
    localeKey: 'actions.weekly.flirted',
    area: 'social',
    categories: ['affection'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Talked to a friend',
    localeKey: 'actions.weekly.talkedToFriend',
    area: 'social',
    categories: ['affection'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Navigated on social media',
    localeKey: 'actions.weekly.navigatedSocialMedia',
    area: 'social',
    categories: ['community'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Talked to family',
    localeKey: 'actions.weekly.talkedToFamily',
    area: 'social',
    categories: ['affection'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Made music',
    localeKey: 'actions.weekly.madeMusic',
    area: 'self',
    categories: ['fun'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Meditated',
    localeKey: 'actions.weekly.meditated',
    area: 'self',
    categories: ['spirituality'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Spoke to the holy',
    localeKey: 'actions.weekly.spokeToHoly',
    area: 'self',
    categories: ['spirituality'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Read a mystic book',
    localeKey: 'actions.weekly.readMysticBook',
    area: 'self',
    categories: ['spirituality'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Shared learnings',
    localeKey: 'actions.weekly.sharedLearnings',
    area: 'social',
    categories: ['community'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Studied a subject',
    localeKey: 'actions.weekly.studiedSubject',
    area: 'self',
    categories: ['growth'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Watched some educational content',
    localeKey: 'actions.weekly.watchedEducational',
    area: 'self',
    categories: ['growth'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Played a game',
    localeKey: 'actions.weekly.playedGame',
    area: 'self',
    categories: ['fun'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Watched series or film',
    localeKey: 'actions.weekly.watchedSeries',
    area: 'self',
    categories: ['fun'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Read news',
    localeKey: 'actions.weekly.readNews',
    area: 'social',
    categories: ['community'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Wrote an opinion',
    localeKey: 'actions.weekly.wroteOpinion',
    area: 'social',
    categories: ['community'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Cleaned bed',
    localeKey: 'actions.weekly.cleanedBed',
    area: 'home',
    categories: ['clean'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Ensured bedroom is ordered',
    localeKey: 'actions.weekly.orderedBedroom',
    area: 'home',
    categories: ['clean'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Shaved body',
    localeKey: 'actions.weekly.shavedBody',
    area: 'home',
    categories: ['clean', 'extra'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Shaved face',
    localeKey: 'actions.weekly.shavedFace',
    area: 'home',
    categories: ['clean', 'extra'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Cut nails',
    localeKey: 'actions.weekly.cutNails',
    area: 'home',
    categories: ['clean', 'extra'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Brushed surfaces',
    localeKey: 'actions.weekly.brushedSurfaces',
    area: 'home',
    categories: ['clean', 'extra'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Mopped floors',
    localeKey: 'actions.weekly.moppedFloors',
    area: 'home',
    categories: ['clean', 'extra'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Washed clothes',
    localeKey: 'actions.weekly.washedClothes',
    area: 'home',
    categories: ['clean', 'extra'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Cleaned bathroom',
    localeKey: 'actions.weekly.cleanedBathroom',
    area: 'home',
    categories: ['clean', 'extra'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Cleaned kitchen',
    localeKey: 'actions.weekly.cleanedKitchen',
    area: 'home',
    categories: ['clean', 'extra'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Worked on personal project',
    localeKey: 'actions.weekly.personalProject',
    area: 'self',
    categories: ['work'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Helped someone',
    localeKey: 'actions.weekly.helpedSomeone',
    area: 'social',
    categories: ['community'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
  {
    name: 'Bought groceries',
    localeKey: 'actions.weekly.boughtGroceries',
    area: 'home',
    categories: ['maintenance'],
    cadence: 'weekly',
    status: "Not started",
    times: 1,
    count: 0,
  },
]


export const DAILY_ACTIONS = [
  {
    name: 'Drank Water',
    localeKey: 'actions.daily.drankWater',
    area: 'self',
    categories: ['body'],
    cadence: 'daily',
    status: 'Not started',
    times: 1,
    count: 0,
  },
  {
    name: 'Showered',
    localeKey: 'actions.daily.showered',
    area: 'self',
    categories: ['body'],
    cadence: 'daily',
    status: 'Not started',
    times: 1,
    count: 0,
  },
  {
    name: 'Took meds',
    localeKey: 'actions.daily.tookMeds',
    area: 'self',
    categories: ['body'],
    cadence: '2-daily',
    status: 'Not started',
    times: 1,
    count: 0,
  },
  {
    name: 'Logged mood',
    localeKey: 'actions.daily.loggedMood',
    area: 'self',
    categories: ['body'],
    cadence: 'daily',
    status: 'Not started',
    times: 1,
    count: 0,
  },
  {
    name: 'Ate breakfast',
    localeKey: 'actions.daily.ateBreakfast',
    area: 'self',
    categories: ['body'],
    cadence: 'daily',
    status: 'Not started',
    times: 1,
    count: 0,
  },
  {
    name: 'Ate lunch',
    localeKey: 'actions.daily.ateLunch',
    area: 'self',
    categories: ['body'],
    cadence: 'daily',
    status: 'Not started',
    times: 1,
    count: 0,
  },
  {
    name: 'Ate dinner',
    localeKey: 'actions.daily.ateDinner',
    area: 'self',
    categories: ['body'],
    cadence: 'daily',
    status: 'Not started',
    times: 1,
    count: 0,
  },
  {
    name: 'Brushed teeth',
    localeKey: 'actions.daily.brushedTeeth',
    area: 'self',
    categories: ['body'],
    cadence: 'daily',
    status: 'Not started',
    times: 1,
    count: 0,
  },
  {
    name: 'Worked-out',
    localeKey: 'actions.daily.workedOut',
    area: 'self',
    categories: ['body'],
    cadence: 'daily',
    status: 'Not started',
    times: 1,
    count: 0,
  },
  {
    name: 'Worked',
    localeKey: 'actions.daily.worked',
    area: 'home',
    categories: ['work'],
    cadence: 'daily',
    status: 'Not started',
    times: 1,
    count: 0,
  },
  {
    name: 'Washed dishes',
    localeKey: 'actions.daily.washedDishes',
    area: 'home',
    categories: ['clean'],
    cadence: 'daily',
    status: 'Not started',
    times: 1,
    count: 0,
  },
  {
    name: 'Stored dishes',
    localeKey: 'actions.daily.storedDishes',
    area: 'home',
    categories: ['clean'],
    cadence: 'daily',
    status: 'Not started',
    times: 1,
    count: 0,
  },
  {
    name: 'Checked trash',
    localeKey: 'actions.daily.checkedTrash',
    area: 'home',
    categories: ['clean'],
    cadence: 'daily',
    status: 'Not started',
    times: 1,
    count: 0,
  },
  {
    name: 'Brushed floor',
    localeKey: 'actions.daily.brushedFloor',
    area: 'home',
    categories: ['clean'],
    cadence: 'daily',
    status: 'Not started',
    times: 1,
    count: 0,
  },
  {
    name: 'Made love',
    localeKey: 'actions.daily.madeLove',
    area: 'self',
    categories: ['body'],
    cadence: 'daily',
    status: 'Not started',
    times: 1,
    count: 0,
  },
  {
    name: 'Went out',
    localeKey: 'actions.daily.wentOut',
    area: 'social',
    categories: ['community'],
    cadence: 'daily',
    status: 'Not started',
    times: 1,
    count: 0,
  },
]

export const WEEKS = {
  W30: {
    year: 2025,
    week: 29,
    startDay: "2025-07-20",
    endDay: "2025-07-26",
    earnings: 282.00,
    tasks: WEEKLY_ACTIONS
  },
  W29: {
    year: 2025,
    week: 30,
    startDay: "2025-07-27",
    endDay: "2025-08-03",
    earnings: 280.00,
    tasks: WEEKLY_ACTIONS
  },
}

// Utility function to get localized task name
export function getLocalizedTaskName(task: any, t: (key: string) => string): string {
  // If the task has a localeKey, try to translate it
  if (task.localeKey) {
    const translatedName = t(task.localeKey)
    // If translation returns the same key, it means the translation doesn't exist
    // In that case, fall back to the original name
    if (translatedName !== task.localeKey) {
      return translatedName
    }
  }
  
  // Fall back to the original name for custom tasks or missing translations
  return task.name
}

// Utility function to get localized task names for an array of tasks
export function getLocalizedTaskNames(tasks: any[], t: (key: string) => string): any[] {
  return tasks.map(task => ({
    ...task,
    displayName: getLocalizedTaskName(task, t)
  }))
}
