export const locales = ['ar', 'bn', 'ca', 'cs', 'da', 'de', 'el', 'en', 'es', 'et', 'eu', 'fi', 'fr', 'gl', 'ha', 'he', 'hi', 'hu', 'it', 'ja', 'ko', 'ms', 'nl', 'pa', 'pl', 'pt', 'ro', 'ru', 'sv', 'sw', 'tr', 'yo', 'zh']
export const defaultLocale = 'en'

export const WEEKLY_ACTIONS = [
  {
    name: 'Created content for social media',
    localeKey: 'createdContent',
    area: 'social',
    categories: ['community'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Flirted with someone',
    localeKey: 'flirted',
    area: 'social',
    categories: ['affection'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Talked to a friend',
    localeKey: 'talkedToFriend',
    area: 'social',
    categories: ['affection'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Navigated on social media',
    localeKey: 'navigatedSocialMedia',
    area: 'social',
    categories: ['community'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Talked to family',
    localeKey: 'talkedToFamily',
    area: 'social',
    categories: ['affection'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Made music',
    localeKey: 'madeMusic',
    area: 'self',
    categories: ['fun'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Meditated',
    localeKey: 'meditated',
    area: 'self',
    categories: ['spirituality'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Spoke to the holy',
    localeKey: 'spokeToHoly',
    area: 'self',
    categories: ['spirituality'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Read a mystic book',
    localeKey: 'readMysticBook',
    area: 'self',
    categories: ['spirituality'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Shared learnings',
    localeKey: 'sharedLearnings',
    area: 'social',
    categories: ['community'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Studied a subject',
    localeKey: 'studiedSubject',
    area: 'self',
    categories: ['growth'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Watched some educational content',
    localeKey: 'watchedEducational',
    area: 'self',
    categories: ['growth'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Played a game',
    localeKey: 'playedGame',
    area: 'self',
    categories: ['fun'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Watched series or film',
    localeKey: 'watchedSeries',
    area: 'self',
    categories: ['fun'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Read news',
    localeKey: 'readNews',
    area: 'social',
    categories: ['community'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Wrote an opinion',
    localeKey: 'wroteOpinion',
    area: 'social',
    categories: ['community'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Cleaned bed',
    localeKey: 'cleanedBed',
    area: 'home',
    categories: ['clean'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Ensured bedroom is ordered',
    localeKey: 'orderedBedroom',
    area: 'home',
    categories: ['clean'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Shaved body',
    localeKey: 'shavedBody',
    area: 'home',
    categories: ['clean', 'extra'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Shaved face',
    localeKey: 'shavedFace',
    area: 'home',
    categories: ['clean', 'extra'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Cut nails',
    localeKey: 'cutNails',
    area: 'home',
    categories: ['clean', 'extra'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Brushed surfaces',
    localeKey: 'brushedSurfaces',
    area: 'home',
    categories: ['clean', 'extra'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Mopped floors',
    localeKey: 'moppedFloors',
    area: 'home',
    categories: ['clean', 'extra'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Washed clothes',
    localeKey: 'washedClothes',
    area: 'home',
    categories: ['clean', 'extra'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Cleaned bathroom',
    localeKey: 'cleanedBathroom',
    area: 'home',
    categories: ['clean', 'extra'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Cleaned kitchen',
    localeKey: 'cleanedKitchen',
    area: 'home',
    categories: ['clean', 'extra'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Worked on personal project',
    localeKey: 'personalProject',
    area: 'self',
    categories: ['work'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Helped someone',
    localeKey: 'helpedSomeone',
    area: 'social',
    categories: ['community'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
  {
    name: 'Bought groceries',
    localeKey: 'boughtGroceries',
    area: 'home',
    categories: ['maintenance'],
    cadence: 'weekly',
    status: "open",
    times: 1,
    count: 0,
  },
]


export const DAILY_ACTIONS = [
  {
    name: 'Drank Water',
    localeKey: 'drankWater',
    area: 'self',
    categories: ['body'],
    cadence: 'daily',
    status: 'open',
    times: 1,
    count: 0,
  },
  {
    name: 'Showered',
    localeKey: 'showered',
    area: 'self',
    categories: ['body'],
    cadence: 'daily',
    status: 'open',
    times: 1,
    count: 0,
  },
  {
    name: 'Took meds',
    localeKey: 'tookMeds',
    area: 'self',
    categories: ['body'],
    cadence: '2-daily',
    status: 'open',
    times: 1,
    count: 0,
  },
  {
    name: 'Logged mood',
    localeKey: 'loggedMood',
    area: 'self',
    categories: ['body'],
    cadence: 'daily',
    status: 'open',
    times: 1,
    count: 0,
  },
  {
    name: 'Ate breakfast',
    localeKey: 'ateBreakfast',
    area: 'self',
    categories: ['body'],
    cadence: 'daily',
    status: 'open',
    times: 1,
    count: 0,
  },
  {
    name: 'Ate lunch',
    localeKey: 'ateLunch',
    area: 'self',
    categories: ['body'],
    cadence: 'daily',
    status: 'open',
    times: 1,
    count: 0,
  },
  {
    name: 'Ate dinner',
    localeKey: 'ateDinner',
    area: 'self',
    categories: ['body'],
    cadence: 'daily',
    status: 'open',
    times: 1,
    count: 0,
  },
  {
    name: 'Brushed teeth',
    localeKey: 'brushedTeeth',
    area: 'self',
    categories: ['body'],
    cadence: 'daily',
    status: 'open',
    times: 1,
    count: 0,
  },
  {
    name: 'Worked-out',
    localeKey: 'workedOut',
    area: 'self',
    categories: ['body'],
    cadence: 'daily',
    status: 'open',
    times: 1,
    count: 0,
  },
  {
    name: 'Worked',
    localeKey: 'worked',
    area: 'home',
    categories: ['work'],
    cadence: 'daily',
    status: 'open',
    times: 1,
    count: 0,
  },
  {
    name: 'Washed dishes',
    localeKey: 'washedDishes',
    area: 'home',
    categories: ['clean'],
    cadence: 'daily',
    status: 'open',
    times: 1,
    count: 0,
  },
  {
    name: 'Stored dishes',
    localeKey: 'storedDishes',
    area: 'home',
    categories: ['clean'],
    cadence: 'daily',
    status: 'open',
    times: 1,
    count: 0,
  },
  {
    name: 'Checked trash',
    localeKey: 'checkedTrash',
    area: 'home',
    categories: ['clean'],
    cadence: 'daily',
    status: 'open',
    times: 1,
    count: 0,
  },
  {
    name: 'Brushed floor',
    localeKey: 'brushedFloor',
    area: 'home',
    categories: ['clean'],
    cadence: 'daily',
    status: 'open',
    times: 1,
    count: 0,
  },
  {
    name: 'Made love',
    localeKey: 'madeLove',
    area: 'self',
    categories: ['body'],
    cadence: 'daily',
    status: 'open',
    times: 1,
    count: 0,
  },
  {
    name: 'Went out',
    localeKey: 'wentOut',
    area: 'social',
    categories: ['community'],
    cadence: 'daily',
    status: 'open',
    times: 1,
    count: 0,
  },
]

export const WEEKS = {
  W30: {
    year: 2025,
    week: 29,
    startDay: "2025-07-20",
    endDay: "2025-07-26",
    earnings: 282.00,
    tasks: WEEKLY_ACTIONS
  },
  W29: {
    year: 2025,
    week: 30,
    startDay: "2025-07-27",
    endDay: "2025-08-03",
    earnings: 280.00,
    tasks: WEEKLY_ACTIONS
  },
}

// Utility function to get localized task name
export function getLocalizedTaskName(task: any, t: (key: string) => string): string {
  // If the task has a localeKey, try to translate it
  if (task.localeKey) {
    const translatedName = t(task.localeKey)
    // If translation returns the same key, it means the translation doesn't exist
    // In that case, fall back to the original name
    if (translatedName !== task.localeKey) {
      return translatedName
    }
  }
  
  // Fall back to the original name for custom tasks or missing translations
  return task.name
}

// Utility function to get localized task names for an array of tasks
export function getLocalizedTaskNames(tasks: any[], t: (key: string) => string): any[] {
  return tasks.map(task => ({
    ...task,
    displayName: getLocalizedTaskName(task, t)
  }))
}
